### ISSUE TITLE
Check Parquet schema mismatch 0.225 > 0.226

### ISSUE THREAD

**Issue by tarigancana** [prestodb/presto#14730]
Hi,
I just upgraded our presto version from 0.225 to 0.235 and found some error while querying the same query before.
`The column duration_from_duration is declared as type bigint, but the Parquet file declares the column as type INT32`

I just check the source and release notes that this changes since 0.226
https://github.com/prestodb/presto/commit/5d18a1c01d048bec435e587887bf20ffbe9794f8

https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetPageSourceFactory.java#L319

Any suggestion how should i fix this problem? as rewrite the parquet file will be take some times.

**Comment by mbasmanova** [comment]
@vkorukanti Venki, would you take a look? Sounds like a recently introduced regression. https://github.com/prestodb/presto/pull/14548

CC: @zhenxiao @rongrong

**Comment by vkorukanti** [comment]
@mbasmanova Actually this issue is fixed by #14548 , but it is available in 0.236. @tarigancana Either you can cherry-pick #14548 or move to 0.236.

**Comment by tarigancana** [comment]
Thanks for response @vkorukanti will check on 0.236 and update the issue later

**Comment by tarigancana** [comment]
hi @vkorukanti & @mbasmanova I just update the presto to 0.236 and confirm that this issue is not happen again..
But i found another issue that our Hive Metastore cpu is goes to 100% and also make the Out of Memory

```
2020-06-28T06:36:40,948 ERROR [pool-7-thread-193] metastore.RetryingHMSHandler: Retrying HMSHandler after 2000 ms (attempt 1 of 10) with error: javax.jdo.JDOException: Exception thrown when executing query : SELECT "A0"."PART_NAME" FROM "
PARTITIONS" "A0" LEFT OUTER JOIN "TBLS" "B0" ON "A0"."TBL_ID" = "B0"."TBL_ID" LEFT OUTER JOIN "DBS" "C0" ON "B0"."DB_ID" = "C0"."DB_ID" WHERE "C0"."NAME" = ? AND "B0"."TBL_NAME" = ? AND "A0"."PART_NAME" LIKE 'event=%/ts=%' ESCAPE E'\\'
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:677)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:391)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:255)
        at org.apache.hadoop.hive.metastore.ObjectStore.getPartitionPsQueryResults(ObjectStore.java:2565)
        at org.apache.hadoop.hive.metastore.ObjectStore.listPartitionNamesPs(ObjectStore.java:2612)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:101)
        at com.sun.proxy.$Proxy23.listPartitionNamesPs(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_partition_names_ps(HiveMetaStore.java:4517)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:148)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107)
        at com.sun.proxy.$Proxy24.get_partition_names_ps(Unknown Source)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12389)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12373)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:103)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
NestedThrowablesStackTrace:
org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1969)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
        at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:552)
        at org.datanucleus.store.rdbms.query.JDOQLQuery.performExecute(JDOQLQuery.java:617)
        at org.datanucleus.store.query.Query.executeQuery(Query.java:1855)
        at org.datanucleus.store.query.Query.executeWithArray(Query.java:1744)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:368)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:255)
        at org.apache.hadoop.hive.metastore.ObjectStore.getPartitionPsQueryResults(ObjectStore.java:2565)
        at org.apache.hadoop.hive.metastore.ObjectStore.listPartitionNamesPs(ObjectStore.java:2612)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:101)
        at com.sun.proxy.$Proxy23.listPartitionNamesPs(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_partition_names_ps(HiveMetaStore.java:4517)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:148)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107)
        at com.sun.proxy.$Proxy24.get_partition_names_ps(Unknown Source)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12389)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12373)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:103)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I also try update to 0.237 and the problem still happen. any suggestion?

![Screen Shot 2020-06-28 at 13 43 04](https://user-images.githubusercontent.com/11748229/85940218-56e5bc80-b945-11ea-9e75-a50e14c5ed0c.png)

**Comment by mbasmanova** [comment]
@tarigancana Rancana, since the original issue is fixed, let's close this issue and open a separate one for the new issues you are seeing.

For the 100% CPU utilization and out-of-memory issue in Hive Metastore: @vkorukanti Venki, are there any new calls to the metastore or have the frequency of existing calls changed? Rancana, use [async profiler](https://github.com/jvm-profiling-tools/async-profiler) to determine where the CPU time goes. If you haven't used it before, let me know and I'll walk you though it. You'd need to run a couple of commands:

* `./profiler.sh -d 30 -e cpu -f /tmp/cpu_profile.txt PID`
* `./profiler.sh -d 30 -e alloc -f /tmp/alloc_profile.txt PID`

, where PID is the process ID of the Hive Metastore process that goes to 100% CPU and runs out of memory. The first command will collect CPU profile and the second - memory profile. You can also change the output file to have .svg extension and it will generate a flamechart, but if you'd like me to take a look at the profiles, please, generate them in plain text format.

Also, google shows up this blog re: OOMs in Hive Metastore - https://luminousmen.com/post/hive-gc-overhead-limit-exceeded

**Comment by tarigancana** [comment]
@mbasmanova let me try that profiling to find the root cause of this problem
i just open new issue related to this OOM https://github.com/prestodb/presto/issues/14749
so we can closed this issue :)
