### ISSUE TITLE
GSS initiate failed

### ISSUE THREAD

**Issue by mouendless** [prestodb/presto#5709]
I encountered an error when query on a 300m large table in parquet. It's an occasionally  error, I paste the failed and success console both bellow.

BTW, when I use hive for the same query on the same table, the error never occurred, which makes I believe the table has no problem. 
## Failed output

```
$presto:dt_general_statistics> select count(*) from events_parquet_300m;

Query 20160720_064615_00014_hmv34, FAILED, 7 nodes
Splits: 94 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160720_064615_00014_hmv34 failed: Error opening Hive split hdfs://longzhou-hdpnn.lz.dscc:11000/user/dt/hive-warehouse/dt_general_statistics.db/events_parquet_300m/part-r-00002-3a704be0-bdc2-4a41-a430-60222e023e9c.gz.parquet (offset=0, length=61349590): GSS initiate failed
```
## Success output

```
$presto:dt_general_statistics> select count(*) from events_parquet_300m;
   _col0    
------------
 3128156080 
(1 row)

Query 20160720_064618_00015_hmv34, FINISHED, 7 nodes
Splits: 1,001 total, 1,001 done (100.00%)
0:06 [3.13B rows, 49.2GB] [510M rows/s, 8.02GB/s]
```

**Comment by electrum** [comment]
Can you show the full stack trace for the failure? You can get that from the CLI by running with `--debug` or in the web UI.

**Comment by mouendless** [comment]
@electrum here are the full stacks

$presto:dt_general_statistics> select count(*) from events_parquet_300m;

Query 20160721_004959_00002_hmv34, FAILED, 7 nodes
http://192.168.19.107:38080/query.html?20160721_004959_00002_hmv34
Splits: 487 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 1% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160721_004959_00002_hmv34 failed: Error opening Hive split hdfs://longzhou-hdpnn.lz.dscc:11000/user/dt/hive-warehouse/dt_general_statistics.db/events_parquet_300m/part-r-00274-3a704be0-bdc2-4a41-a430-60222e023e9c.gz.parquet (offset=0, length=51756767): GSS initiate failed
com.facebook.presto.spi.PrestoException: Error opening Hive split hdfs://longzhou-hdpnn.lz.dscc:11000/user/dt/hive-warehouse/dt_general_statistics.db/events_parquet_300m/part-r-00274-3a704be0-bdc2-4a41-a430-60222e023e9c.gz.parquet (offset=0, length=51756767): GSS initiate failed
        at com.facebook.presto.hive.parquet.HdfsParquetDataSource.buildHdfsParquetDataSource(HdfsParquetDataSource.java:105)
        at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:414)
        at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:246)
        at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:96)
        at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:129)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:107)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
        at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:268)
        at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:210)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:375)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException: GSS initiate failed
        at org.apache.hadoop.ipc.Client.call(Client.java:1476)
        at org.apache.hadoop.ipc.Client.call(Client.java:1407)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy170.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy171.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2116)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
        at com.facebook.presto.hive.parquet.HdfsParquetDataSource.buildHdfsParquetDataSource(HdfsParquetDataSource.java:96)
        ... 17 more

**Comment by zhoushineyoung** [comment]
I also encountered this problem, some other configurations need to be set? Or anything else?

**Comment by wikp** [comment]
Same bug here. Noticed that it fails after opening CLI interface (or after log in into Airpal) but after few tries suddenly starts to work like a charm. Stack trace below. I'll be working on a solution but currently I don't know Presto's codebase so I need to dive in into it ;)

```
Query 20161209_113357_00002_zm3xa, FAILED, 24 nodes
http://localhost:8080/query.html?20161209_113357_00002_zm3xa
Splits: 7,866 total, 6,686 done (85.00%)
CPU Time: 4647.3s total,  671K rows/s,  137MB/s, 3% active
Per Node: 2.1 parallelism, 1.39M rows/s,  283MB/s
Parallelism: 49.8
1:33 [3.12B rows, 620GB] [33.4M rows/s, 6.63GB/s]

Query 20161209_113357_00002_zm3xa failed: Error opening Hive split hdfs://{removed :)}/part-00040 (offset=0, length=125715962): GSS initiate failed
com.facebook.presto.spi.PrestoException: Error opening Hive split hdfs://{removed :)}/part-00040 (offset=0, length=125715962): GSS initiate failed
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:385)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:157)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:92)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:155)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:213)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException: GSS initiate failed
	at org.apache.hadoop.ipc.Client.call(Client.java:1475)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy187.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2108)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:385)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.lambda$createParquetRecordReader$0(ParquetHiveRecordCursor.java:332)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1678)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at com.facebook.presto.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:38)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:76)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:332)
	... 15 more

```

**Comment by haozhun** [comment]
I closed #6959 which attempts to fix this issue by retry. We need Kerberos experts to investigate and understand this issue. We want to understand the overall problem. Unless we conclude that retry is the only feasible way to fix this after investigation, we would prefer a different approach.

**Comment by electrum** [comment]
We just merged a fix for the "Filesystem closed" issue (#8955) that might possibly be related.

How long has the cluster been running when this error first occurs? I'm wondering if it always occurs at a fixed interval, say the one hour mark, after the cluster is restarted.

**Comment by mouendless** [comment]
Sry for late reply. We update the cluster to 0.161 and the bug not appeared again. And furthermore when update to 0.184, the query get much faster.

**Comment by vloup** [comment]
I got this issue this morning on a cluster running version 0.185 (the cluster has been up during the weekend). Restarting the nodes throwing errors was the only solution to make the query pass. I do not recall having such an issue with previous versions (we upgraded last week from 0.183 in the unsuccessful hope to get rid of `Filesystem Closed` errors).

Coordinator log:
```
2017-10-02T07:50:28.540Z        DEBUG   query-execution-0       com.facebook.presto.execution.StageStateMachine Stage 20171002_075024_00001_yhikj.1 is FAILED
2017-10-02T07:50:28.540Z        ERROR   remote-task-callback-7  com.facebook.presto.execution.StageStateMachine Stage 20171002_075024_00001_yhikj.1 failed
com.facebook.presto.spi.PrestoException: Error opening Hive split hdfs://mycluster/apps/hive/warehouse/HIDDEN/000002_0 (offset=201326592, length=33554432): GSS initiate failed
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:176)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createPageSource(OrcPageSourceFactory.java:112)
        at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:135)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:88)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException: GSS initiate failed
        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy171.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
        at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy172.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:160)
        ... 17 more
2017-10-02T07:50:28.540Z        DEBUG   remote-task-callback-10 com.facebook.presto.execution.StageStateMachine Failure after stage 20171002_075024_00001_yhikj.1 finished
com.facebook.presto.spi.PrestoException: Error opening Hive split hdfs://mycluster/apps/hive/warehouse/HIDDEN/000003_0 (offset=0, length=33554432): GSS initiate failed
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:176)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createPageSource(OrcPageSourceFactory.java:112)
        at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:135)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:88)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException: GSS initiate failed
        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy171.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
        at sun.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy172.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:160)
        ... 17 more
2017-10-02T07:50:28.542Z        DEBUG   query-execution-1       com.facebook.presto.execution.QueryStateMachine Query 20171002_075024_00001_yhikj is FAILED
2017-10-02T07:50:28.542Z        DEBUG   query-execution-0       com.facebook.presto.execution.QueryStateMachine Query 20171002_075024_00001_yhikj failed
com.facebook.presto.spi.PrestoException: Error opening Hive split hdfs://mycluster/apps/hive/warehouse/HIDDEN/000002_0 (offset=201326592, length=33554432): GSS initiate failed
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:176)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createPageSource(OrcPageSourceFactory.java:112)
        at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:135)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:88)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException: GSS initiate failed
        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy171.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
        at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy172.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
        at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:160)
        ... 17 more

		
2017-10-02T07:50:28.543Z        DEBUG   query-execution-2       com.facebook.presto.execution.StageStateMachine Stage 20171002_075024_00001_yhikj.0 is ABORTED
2017-10-02T07:50:28.563Z        DEBUG   http-worker-142 com.facebook.presto.execution.SqlTask   Aborting task 20171002_075024_00001_yhikj.1.9 output 0
2017-10-02T07:50:28.565Z        DEBUG   task-notification-0     com.facebook.presto.execution.TaskStateMachine  Task 20171002_075024_00001_yhikj.1.9 is CANCELED
2017-10-02T07:50:28.661Z        DEBUG   exchange-client-7       com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4480/v1/task/20171002_075024_00001_yhikj.0.0/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:28.715Z        INFO    query-execution-1       com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171002_075024_00001_yhikj :: Transaction:[95eefe96-36e1-4be9-9c12-352b2a0505a4] :: elapsed 3551ms :: planning 567ms :: scheduling 0ms :: running 29378ms :: finishing 0ms :: begin 2017-10-02T07:50:24.990Z :: end 2017-10-02T07:50:28.541Z
```

One of the affected worker node (2 of them failed out of 11 according to the web panel):
```
2017-10-02T07:50:21.135Z        ERROR   SplitRunner-516-98      com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20171002_075024_00001_yhikj.1.10-4 {path=hdfs://mycluster/apps/hive/warehouse/HIDDEN/000002_0, start=201326592, length=33554432, fileSize=512660393, hosts=[datanode-dc1r04n04.hostname.tld, datanode-dc1r05n05.hostname.tld, datanode-dc1r05n03.hostname.tld], database=HIDDEN, table=HIDDEN, forceLocalScheduling=false, partitionName=<UNPARTITIONED>} (start = 1.36096499369273E10, wall = 11 ms, cpu = 0 ms, wait = 1 ms, calls = 1): HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split hdfs://mycluster/apps/hive/warehouse/HIDDEN/000002_0 (offset=201326592, length=33554432): GSS initiate failed
2017-10-02T07:50:21.139Z        DEBUG   task-notification-0     com.facebook.presto.execution.TaskStateMachine  Task 20171002_075024_00001_yhikj.1.10 is FAILED
2017-10-02T07:50:21.140Z        DEBUG   task-notification-0     com.facebook.presto.execution.executor.TaskExecutor     Task finished or failed 20171002_075024_00001_yhikj.1.10
2017-10-02T07:50:21.174Z        DEBUG   exchange-client-4       com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4480/v1/task/20171002_075024_00001_yhikj.1.7/results/0/15 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:21.174Z        DEBUG   20171002_075024_00001_yhikj.0.0-16-106  com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-16  (start = 1.3609647046025156E10, wall = 2940 ms, cpu = 1 ms, wait = 11 ms, calls = 2) is finished
2017-10-02T07:50:21.175Z        DEBUG   exchange-client-14      com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4480/v1/task/20171002_075024_00001_yhikj.1.2/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:21.178Z        DEBUG   exchange-client-2       com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4481/v1/task/20171002_075024_00001_yhikj.1.9/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:21.178Z        DEBUG   exchange-client-24      com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4480/v1/task/20171002_075024_00001_yhikj.1.10/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:21.183Z        DEBUG   exchange-client-20      com.facebook.presto.operator.HttpPageBufferClient       Request to http://HIDDEN:4480/v1/task/20171002_075024_00001_yhikj.1.4/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2017-10-02T07:50:21.185Z        DEBUG   http-worker-19486       com.facebook.presto.execution.SqlTask   Aborting task 20171002_075024_00001_yhikj.1.10 output 0
2017-10-02T07:50:21.189Z        DEBUG   20171002_075024_00001_yhikj.0.0-10-6349 com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-10  (start = 1.3609647044389357E10, wall = 2957 ms, cpu = 1 ms, wait = 8 ms, calls = 3) is finished
2017-10-02T07:50:21.190Z        DEBUG   20171002_075024_00001_yhikj.0.0-9-93    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-9  (start = 1.3609647043355944E10, wall = 2959 ms, cpu = 4 ms, wait = 7 ms, calls = 3) is finished
2017-10-02T07:50:21.195Z        DEBUG   20171002_075024_00001_yhikj.0.0-15-102  com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-15  (start = 1.3609647045931044E10, wall = 2961 ms, cpu = 1 ms, wait = 21 ms, calls = 3) is finished
2017-10-02T07:50:21.198Z        DEBUG   20171002_075024_00001_yhikj.0.0-2-99    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-2  (start = 1.3609647041909779E10, wall = 2968 ms, cpu = 2 ms, wait = 5 ms, calls = 4) is finished
2017-10-02T07:50:21.200Z        DEBUG   20171002_075024_00001_yhikj.0.0-11-47   com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-11  (start = 1.3609647044482164E10, wall = 2967 ms, cpu = 1 ms, wait = 3 ms, calls = 3) is finished
2017-10-02T07:50:21.200Z        DEBUG   20171002_075024_00001_yhikj.0.0-4-6316  com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-4  (start = 1.3609647042852022E10, wall = 2969 ms, cpu = 1 ms, wait = 6 ms, calls = 3) is finished
2017-10-02T07:50:21.198Z        DEBUG   20171002_075024_00001_yhikj.0.0-1-97    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-1  (start = 1.360964704166152E10, wall = 2969 ms, cpu = 2 ms, wait = 0 ms, calls = 3) is finished
2017-10-02T07:50:21.200Z        DEBUG   20171002_075024_00001_yhikj.0.0-13-80   com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-13  (start = 1.3609647045866863E10, wall = 2966 ms, cpu = 1 ms, wait = 17 ms, calls = 3) is finished
2017-10-02T07:50:21.201Z        DEBUG   20171002_075024_00001_yhikj.0.0-0-77    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-0  (start = 1.3609647041658806E10, wall = 2972 ms, cpu = 2 ms, wait = 0 ms, calls = 3) is finished
2017-10-02T07:50:21.201Z        DEBUG   20171002_075024_00001_yhikj.0.0-8-46    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-8  (start = 1.360964704332691E10, wall = 2970 ms, cpu = 2 ms, wait = 7 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-14-71   com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-14  (start = 1.360964704589869E10, wall = 2968 ms, cpu = 1 ms, wait = 17 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-3-6124  com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-3  (start = 1.3609647042831097E10, wall = 2971 ms, cpu = 2 ms, wait = 2 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-12-96   com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-12  (start = 1.3609647044493628E10, wall = 2969 ms, cpu = 2 ms, wait = 7 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-7-6127  com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-7  (start = 1.3609647043150246E10, wall = 2971 ms, cpu = 1 ms, wait = 10 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-6-107   com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-6  (start = 1.3609647043091043E10, wall = 2971 ms, cpu = 1 ms, wait = 9 ms, calls = 3) is finished
2017-10-02T07:50:21.202Z        DEBUG   20171002_075024_00001_yhikj.0.0-5-78    com.facebook.presto.execution.executor.TaskExecutor     Split 20171002_075024_00001_yhikj.0.0-5  (start = 1.3609647042940536E10, wall = 2972 ms, cpu = 1 ms, wait = 9 ms, calls = 3) is finished
2017-10-02T07:50:21.203Z        DEBUG   task-notification-0     com.facebook.presto.execution.TaskStateMachine  Task 20171002_075024_00001_yhikj.0.0 is ABORTED
2017-10-02T07:50:21.203Z        DEBUG   task-notification-0     com.facebook.presto.execution.executor.TaskExecutor     Task finished or failed 20171002_075024_00001_yhikj.0.0
2017-10-02T07:50:21.284Z        DEBUG   http-worker-19486       com.facebook.presto.execution.SqlTask   Aborting task 20171002_075024_00001_yhikj.0.0 output 0
```

**Comment by qgxiaozhan** [comment]
I use master branch , And it still happen.

**Comment by qgxiaozhan** [comment]
@electrum  I Used  0.187 and it still happened , I think we should open it and found out the reason.

**Comment by mouendless** [comment]
Since there still exist users encountering this problem for version after 0.184, I reopen this issue and see whether it can be resolved.

**Comment by vloup** [comment]
So far, I got this issue only once. I do not know what caused this issue, and I do not know how to reproduce this. Does @qgxiaozhan knows how to reproduce it?

**Comment by qgxiaozhan** [comment]
@vloup  sorry , I have not idea now !

**Comment by qgxiaozhan** [comment]
@vloup This guy add a cache to hold the fs [#20](https://github.com/hellopower/presto-hadoop-apache2/commit/4db50727c82493153d8bad3710a5fb9f3c9a5efe)

**Comment by vloup** [comment]
@qgxiaozhan I still did not get this "GSS Initiate Failed" issue since last time I reported it (i.e. last October). It is definitely an odd behavior I got. The issue you referenced about the "Filesystem closed" problem has been fixed in release 0.187, and I can doubly confirm it got solved. Anyhow, thanks for your answer.

**Comment by gravitys169** [comment]
I got the same bug again, the GSS initiate failed will happen randomly，the possibility of failed query is bigger than success.

do anyone has any idea now?

**Comment by gravitys169** [comment]
I finally solved this bug.
it is due to the presto worker's /etc/hosts has two hadoop cluster's hostnames,
and unfortunately the two cluster's hostnames has the same name which point to different ip,
such as host0 can point to 129.22.110.1 or 129.22.100.1.
some worker's hosts file is correct, so it can run succefully sometimes.
